language: csharp
sudo: required
dist: xenial

dotnet: 3.0.100
mono:
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux

script:
  - ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: alpha
    - mono: beta
    - mono: weekly
